"""PQRS del servicio de salud y farmacovigilancia

Revision ID: 2a89797919d2
Revises: 2b672fbe63b4
Create Date: 2026-09-07 19:05:04.832586

"""
from alembic import op
import sqlalchemy as sa

# `EncryptedText` es un tipo propio: las migraciones que tocan columnas
# cifradas lo referencian como `security.EncryptedText()`.
import security


# revision identifiers, used by Alembic.
revision = '2a89797919d2'
down_revision = '2b672fbe63b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adverse_drug_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('reported_by_id', sa.Integer(), nullable=True),
    sa.Column('medical_history_id', sa.Integer(), nullable=True),
    sa.Column('medication', security.EncryptedText(), nullable=False),
    sa.Column('medication_normalized', sa.String(length=180), nullable=True),
    sa.Column('cum_code', sa.String(length=30), nullable=True),
    sa.Column('batch_number', sa.String(length=60), nullable=True),
    sa.Column('description', security.EncryptedText(), nullable=False),
    sa.Column('seriousness', sa.String(length=12), nullable=False),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('invima_reference', sa.String(length=60), nullable=True),
    sa.Column('resolution_note', security.EncryptedText(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], name=op.f('fk_adverse_drug_event_clinic_id_clinic')),
    sa.ForeignKeyConstraint(['medical_history_id'], ['medical_history.id'], name=op.f('fk_adverse_drug_event_medical_history_id_medical_history')),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], name=op.f('fk_adverse_drug_event_patient_id_user')),
    sa.ForeignKeyConstraint(['reported_by_id'], ['user.id'], name=op.f('fk_adverse_drug_event_reported_by_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adverse_drug_event'))
    )
    with op.batch_alter_table('adverse_drug_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_adverse_drug_event_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adverse_drug_event_cum_code'), ['cum_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_adverse_drug_event_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_adverse_drug_event_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_adverse_drug_event_medical_history_id'), ['medical_history_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adverse_drug_event_medication_normalized'), ['medication_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_adverse_drug_event_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_adverse_drug_event_seriousness'), ['seriousness'], unique=False)
        batch_op.create_index(batch_op.f('ix_adverse_drug_event_status'), ['status'], unique=False)

    op.create_table('service_complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_code', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('complaint_type', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('detail', security.EncryptedText(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolution', security.EncryptedText(), nullable=True),
    sa.Column('related_history_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], name=op.f('fk_service_complaint_clinic_id_clinic')),
    sa.ForeignKeyConstraint(['related_history_id'], ['medical_history.id'], name=op.f('fk_service_complaint_related_history_id_medical_history')),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['user.id'], name=op.f('fk_service_complaint_resolved_by_id_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_service_complaint_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_complaint'))
    )
    with op.batch_alter_table('service_complaint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_complaint_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_complaint_complaint_type'), ['complaint_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_complaint_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_complaint_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_complaint_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_complaint_ticket_code'), ['ticket_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_complaint_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_complaint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_complaint_user_id'))
        batch_op.drop_index(batch_op.f('ix_service_complaint_ticket_code'))
        batch_op.drop_index(batch_op.f('ix_service_complaint_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_service_complaint_status'))
        batch_op.drop_index(batch_op.f('ix_service_complaint_due_at'))
        batch_op.drop_index(batch_op.f('ix_service_complaint_complaint_type'))
        batch_op.drop_index(batch_op.f('ix_service_complaint_clinic_id'))

    op.drop_table('service_complaint')
    with op.batch_alter_table('adverse_drug_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_adverse_drug_event_status'))
        batch_op.drop_index(batch_op.f('ix_adverse_drug_event_seriousness'))
        batch_op.drop_index(batch_op.f('ix_adverse_drug_event_patient_id'))
        batch_op.drop_index(batch_op.f('ix_adverse_drug_event_medication_normalized'))
        batch_op.drop_index(batch_op.f('ix_adverse_drug_event_medical_history_id'))
        batch_op.drop_index(batch_op.f('ix_adverse_drug_event_due_at'))
        batch_op.drop_index(batch_op.f('ix_adverse_drug_event_detected_at'))
        batch_op.drop_index(batch_op.f('ix_adverse_drug_event_cum_code'))
        batch_op.drop_index(batch_op.f('ix_adverse_drug_event_clinic_id'))

    op.drop_table('adverse_drug_event')
    # ### end Alembic commands ###
