"""Vigilancia en salud publica: eventos notificables al Sivigila

Revision ID: 2b672fbe63b4
Revises: 3d87271539f9
Create Date: 2026-09-07 02:42:31.889465

"""
from alembic import op
import sqlalchemy as sa

# `EncryptedText` es un tipo propio: las migraciones que tocan columnas
# cifradas lo referencian como `security.EncryptedText()`.
import security


# revision identifiers, used by Alembic.
revision = '2b672fbe63b4'
down_revision = '3d87271539f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifiable_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('periodicity', sa.String(length=12), nullable=False),
    sa.Column('cie10_prefixes', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifiable_event'))
    )
    with op.batch_alter_table('notifiable_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifiable_event_code'), ['code'], unique=True)

    op.create_table('sivigila_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_history_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('event_code', sa.String(length=10), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('periodicity', sa.String(length=12), nullable=False),
    sa.Column('cie10_code', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('notified_by_id', sa.Integer(), nullable=True),
    sa.Column('ficha_reference', sa.String(length=60), nullable=True),
    sa.Column('resolution_note', security.EncryptedText(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], name=op.f('fk_sivigila_notification_clinic_id_clinic')),
    sa.ForeignKeyConstraint(['medical_history_id'], ['medical_history.id'], name=op.f('fk_sivigila_notification_medical_history_id_medical_history')),
    sa.ForeignKeyConstraint(['notified_by_id'], ['user.id'], name=op.f('fk_sivigila_notification_notified_by_id_user')),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], name=op.f('fk_sivigila_notification_patient_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sivigila_notification')),
    sa.UniqueConstraint('medical_history_id', 'event_code', name='uq_sivigila_atencion_evento')
    )
    with op.batch_alter_table('sivigila_notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sivigila_notification_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sivigila_notification_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sivigila_notification_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sivigila_notification_event_code'), ['event_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sivigila_notification_medical_history_id'), ['medical_history_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sivigila_notification_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sivigila_notification_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sivigila_notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sivigila_notification_status'))
        batch_op.drop_index(batch_op.f('ix_sivigila_notification_patient_id'))
        batch_op.drop_index(batch_op.f('ix_sivigila_notification_medical_history_id'))
        batch_op.drop_index(batch_op.f('ix_sivigila_notification_event_code'))
        batch_op.drop_index(batch_op.f('ix_sivigila_notification_due_at'))
        batch_op.drop_index(batch_op.f('ix_sivigila_notification_detected_at'))
        batch_op.drop_index(batch_op.f('ix_sivigila_notification_clinic_id'))

    op.drop_table('sivigila_notification')
    with op.batch_alter_table('notifiable_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifiable_event_code'))

    op.drop_table('notifiable_event')
    # ### end Alembic commands ###
