"""Causa externa, finalidad, modalidad, adenda, oportunidad y catalogos RIPS

Revision ID: 3d87271539f9
Revises: f6d60c906bbc
Create Date: 2026-09-07 02:28:23.773398

"""
from alembic import op
import sqlalchemy as sa

# `EncryptedText` es un tipo propio: las migraciones que tocan columnas
# cifradas lo referencian como `security.EncryptedText()`.
import security


# revision identifiers, used by Alembic.
revision = '3d87271539f9'
down_revision = 'f6d60c906bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rips_reference_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=60), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rips_reference_code')),
    sa.UniqueConstraint('table_name', 'code', name='uq_rips_ref_tabla_codigo')
    )
    with op.batch_alter_table('rips_reference_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rips_reference_code_table_name'), ['table_name'], unique=False)

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_appointment_requested_at'), ['requested_at'], unique=False)

    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_cause', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('consultation_purpose', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('care_modality', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('amends_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('amendment_reason', security.EncryptedText(), nullable=True))
        batch_op.create_index(batch_op.f('ix_medical_history_amends_id'), ['amends_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_history_care_modality'), ['care_modality'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_history_external_cause'), ['external_cause'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_medical_history_amends_id_medical_history'), 'medical_history', ['amends_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_medical_history_amends_id_medical_history'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_medical_history_external_cause'))
        batch_op.drop_index(batch_op.f('ix_medical_history_care_modality'))
        batch_op.drop_index(batch_op.f('ix_medical_history_amends_id'))
        batch_op.drop_column('amendment_reason')
        batch_op.drop_column('amends_id')
        batch_op.drop_column('care_modality')
        batch_op.drop_column('consultation_purpose')
        batch_op.drop_column('external_cause')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_requested_at'))
        batch_op.drop_column('requested_at')

    with op.batch_alter_table('rips_reference_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rips_reference_code_table_name'))

    op.drop_table('rips_reference_code')
    # ### end Alembic commands ###
