"""Cola de envio del RDA al IHCE (Resolucion 1888 de 2025)

Revision ID: ce859f34125c
Revises: 8d7b0240d41f
Create Date: 2026-09-07 01:35:47.170661

"""
from alembic import op
import sqlalchemy as sa

# `EncryptedText` es un tipo propio: las migraciones que tocan columnas
# cifradas lo referencian como `security.EncryptedText()`.
import security


# revision identifiers, used by Alembic.
revision = 'ce859f34125c'
down_revision = '8d7b0240d41f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rda_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_history_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('bundle_hash', sa.String(length=64), nullable=True),
    sa.Column('remote_id', sa.String(length=120), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('guide_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], name=op.f('fk_rda_submission_clinic_id_clinic')),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], name=op.f('fk_rda_submission_doctor_id_user')),
    sa.ForeignKeyConstraint(['medical_history_id'], ['medical_history.id'], name=op.f('fk_rda_submission_medical_history_id_medical_history')),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], name=op.f('fk_rda_submission_patient_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rda_submission')),
    sa.UniqueConstraint('medical_history_id', name='uq_rda_por_atencion')
    )
    with op.batch_alter_table('rda_submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rda_submission_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rda_submission_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rda_submission_medical_history_id'), ['medical_history_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rda_submission_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rda_submission_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rda_submission_remote_id'), ['remote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rda_submission_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rda_submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rda_submission_status'))
        batch_op.drop_index(batch_op.f('ix_rda_submission_remote_id'))
        batch_op.drop_index(batch_op.f('ix_rda_submission_patient_id'))
        batch_op.drop_index(batch_op.f('ix_rda_submission_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_rda_submission_medical_history_id'))
        batch_op.drop_index(batch_op.f('ix_rda_submission_created_at'))
        batch_op.drop_index(batch_op.f('ix_rda_submission_clinic_id'))

    op.drop_table('rda_submission')
    # ### end Alembic commands ###
