"""Datos demograficos que exige el perfil PatientRDA

Revision ID: f6d60c906bbc
Revises: ce859f34125c
Create Date: 2026-09-07 01:52:49.783953

"""
from alembic import op
import sqlalchemy as sa

# `EncryptedText` es un tipo propio: las migraciones que tocan columnas
# cifradas lo referencian como `security.EncryptedText()`.
import security


# revision identifiers, used by Alembic.
revision = 'f6d60c906bbc'
down_revision = 'ce859f34125c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality_code', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('ethnic_group', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('disability', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('occupation_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('occupation_code')
        batch_op.drop_column('disability')
        batch_op.drop_column('ethnic_group')
        batch_op.drop_column('nationality_code')

    # ### end Alembic commands ###
