"""Registro SIRAS del usuario (campo U12, Res 948 de 2026)

Revision ID: 2a3878fe5611
Revises: 2a89797919d2
Create Date: 2026-09-07 19:36:34.398215

"""
from alembic import op
import sqlalchemy as sa

# `EncryptedText` es un tipo propio: las migraciones que tocan columnas
# cifradas lo referencian como `security.EncryptedText()`.
import security


# revision identifiers, used by Alembic.
revision = '2a3878fe5611'
down_revision = '2a89797919d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('siras_registration', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('siras_registration')

    # ### end Alembic commands ###
