"""Esquema base con seguridad clinica, libro mayor y habeas data

Revision ID: 2f0500654aaf
Revises: 
Create Date: 2026-09-05 20:44:06.031916

"""
from alembic import op
import sqlalchemy as sa
import security


# revision identifiers, used by Alembic.
revision = '2f0500654aaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('details', security.EncryptedText(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entry_hash'), ['entry_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('cie10',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cie10', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cie10_code'), ['code'], unique=True)

    op.create_table('clinic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('legal_name', sa.String(length=220), nullable=True),
    sa.Column('nit', sa.String(length=50), nullable=True),
    sa.Column('habilitacion_code', sa.String(length=20), nullable=True),
    sa.Column('department_code', sa.String(length=2), nullable=True),
    sa.Column('municipality_code', sa.String(length=3), nullable=True),
    sa.Column('location', sa.String(length=220), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('access_type', sa.String(length=30), nullable=False),
    sa.Column('plan', sa.String(length=80), nullable=False),
    sa.Column('plan_pago', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('contact_email', sa.String(length=180), nullable=True),
    sa.Column('logo_path', sa.String(length=300), nullable=True),
    sa.Column('opening_hours', sa.Text(), nullable=True),
    sa.Column('policy_consent_code', sa.String(length=64), nullable=True),
    sa.Column('policy_consent_generated_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_provider', sa.String(length=80), nullable=True),
    sa.Column('subscription_customer_id', sa.String(length=180), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinic_habilitacion_code'), ['habilitacion_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_policy_consent_code'), ['policy_consent_code'], unique=True)

    op.create_table('cups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cups_code'), ['code'], unique=True)

    op.create_table('jwt_revoked_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jwt_revoked_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jwt_revoked_token_jti'), ['jti'], unique=True)

    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=180), nullable=False),
    sa.Column('institucion', sa.String(length=220), nullable=True),
    sa.Column('telefono', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('ciudad', sa.String(length=120), nullable=True),
    sa.Column('contacto', sa.String(length=300), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_key', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('first_failure_at', sa.DateTime(), nullable=False),
    sa.Column('last_failure_at', sa.DateTime(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempt_attempt_key'), ['attempt_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_login_attempt_locked_until'), ['locked_until'], unique=False)

    op.create_table('patient_doctor_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('plan_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('payment_ticket_id', sa.Integer(), nullable=True),
    sa.Column('policy_enrollment_id', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payment_ticket_id'], ['payment_verification_ticket.id'], ),
    sa.ForeignKeyConstraint(['policy_enrollment_id'], ['user_policy_enrollment.id'], ),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_doctor_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_doctor_subscription_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_doctor_subscription_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_doctor_subscription_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_doctor_subscription_status'), ['status'], unique=False)

    op.create_table('payment_verification_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('final_amount', sa.Float(), nullable=True),
    sa.Column('proof_image', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('patient_note', sa.Text(), nullable=True),
    sa.Column('doctor_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['patient_doctor_subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_verification_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_verification_ticket_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_verification_ticket_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_verification_ticket_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_verification_ticket_status'), ['status'], unique=False)

    op.create_table('policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('insurer_name', sa.String(length=180), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_code'), ['code'], unique=True)

    op.create_table('retention_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=80), nullable=False),
    sa.Column('retention_years', sa.Integer(), nullable=False),
    sa.Column('legal_basis', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retention_policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retention_policy_record_type'), ['record_type'], unique=True)

    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('min_stock', sa.Integer(), nullable=False),
    sa.Column('expires_on', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_item_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('pharmacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('address', sa.String(length=220), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pharmacy_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('nombre_med', sa.String(length=180), nullable=False),
    sa.Column('medicamento', sa.String(length=180), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('cantidad_comprometida', sa.Integer(), nullable=False),
    sa.Column('unidad', sa.String(length=40), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_medicamento'), ['medicamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_nombre_med'), ['nombre_med'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_pharmacy_id'), ['pharmacy_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('name', security.EncryptedText(), nullable=False),
    sa.Column('cedula', security.EncryptedText(), nullable=False),
    sa.Column('cedula_hash', sa.String(length=64), nullable=True),
    sa.Column('phone', security.EncryptedText(), nullable=True),
    sa.Column('email', security.EncryptedText(), nullable=True),
    sa.Column('specialty', sa.String(length=150), nullable=True),
    sa.Column('document_type', sa.String(length=4), nullable=True),
    sa.Column('first_surname', security.EncryptedText(), nullable=True),
    sa.Column('second_surname', security.EncryptedText(), nullable=True),
    sa.Column('first_name', security.EncryptedText(), nullable=True),
    sa.Column('second_name', security.EncryptedText(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('department_code', sa.String(length=2), nullable=True),
    sa.Column('municipality_code', sa.String(length=3), nullable=True),
    sa.Column('zone', sa.String(length=1), nullable=True),
    sa.Column('insurer_code', sa.String(length=20), nullable=True),
    sa.Column('insurer_name', sa.String(length=180), nullable=True),
    sa.Column('affiliation_regime', sa.String(length=30), nullable=True),
    sa.Column('is_pregnant', sa.Boolean(), nullable=False),
    sa.Column('pregnancy_updated_at', sa.DateTime(), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('is_active_account', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('medical_registration', sa.String(length=50), nullable=True),
    sa.Column('signature_path', sa.String(length=300), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('schedule', sa.String(length=200), nullable=True),
    sa.Column('peak_hours', sa.String(length=200), nullable=True),
    sa.Column('avg_response_time', sa.String(length=50), nullable=True),
    sa.Column('avg_consultation_time', sa.String(length=50), nullable=True),
    sa.Column('profile_pic', sa.String(length=300), nullable=True),
    sa.Column('attending_chat_id', sa.Integer(), nullable=True),
    sa.Column('accepted_terms_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_privacy_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_transparency_at', sa.DateTime(), nullable=True),
    sa.Column('sensitive_data_consent_at', sa.DateTime(), nullable=True),
    sa.Column('atencion_inicio', sa.String(length=5), nullable=True),
    sa.Column('atencion_fin', sa.String(length=5), nullable=True),
    sa.Column('address', security.EncryptedText(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_consent_at', sa.DateTime(), nullable=True),
    sa.Column('office_address', security.EncryptedText(), nullable=True),
    sa.Column('office_latitude', sa.Float(), nullable=True),
    sa.Column('office_longitude', sa.Float(), nullable=True),
    sa.Column('show_office_on_map', sa.Boolean(), nullable=False),
    sa.Column('is_autonomous', sa.Boolean(), nullable=False),
    sa.Column('affiliation_type', sa.String(length=30), nullable=False),
    sa.Column('affiliation_name', sa.String(length=180), nullable=True),
    sa.Column('policy_consent_code', sa.String(length=64), nullable=True),
    sa.Column('policy_consent_generated_at', sa.DateTime(), nullable=True),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_cedula_hash'), ['cedula_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_policy_consent_code'), ['policy_consent_code'], unique=True)

    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.Column('appointment_type', sa.String(length=80), nullable=False),
    sa.Column('description', security.EncryptedText(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('clinic_access_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=220), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinic_access_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinic_access_code_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinic_access_code_code'), ['code'], unique=True)

    op.create_table('data_subject_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('detail', security.EncryptedText(), nullable=True),
    sa.Column('resolution_note', security.EncryptedText(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('requester_ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_subject_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_subject_request_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_subject_request_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_subject_request_request_type'), ['request_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_subject_request_requested_at'), ['requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_subject_request_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_subject_request_user_id'), ['user_id'], unique=False)

    op.create_table('doctor_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('specific_date', sa.String(length=10), nullable=True),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_schedule_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('doctor_tariff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('price_per_consultation', sa.Float(), nullable=True),
    sa.Column('price_monthly', sa.Float(), nullable=True),
    sa.Column('price_quarterly', sa.Float(), nullable=True),
    sa.Column('price_annual', sa.Float(), nullable=True),
    sa.Column('default_policy_discount_percent', sa.Float(), nullable=False),
    sa.Column('payment_methods_image', sa.String(length=300), nullable=True),
    sa.Column('payment_instructions', sa.Text(), nullable=True),
    sa.Column('accepts_manual_payment', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_tariff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_tariff_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_tariff_doctor_id'), ['doctor_id'], unique=True)

    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('incoming_shipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=180), nullable=True),
    sa.Column('expected_date', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incoming_shipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incoming_shipment_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incoming_shipment_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incoming_shipment_status'), ['status'], unique=False)

    op.create_table('informed_consent_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('document_version', sa.String(length=30), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('digital_signature_hash', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('informed_consent_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_informed_consent_log_consent_type'), ['consent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_informed_consent_log_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_informed_consent_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('medical_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('meds_json', sa.Text(), nullable=False),
    sa.Column('diagnosis_json', sa.Text(), nullable=True),
    sa.Column('patient_age', sa.String(length=50), nullable=True),
    sa.Column('patient_level', sa.String(length=10), nullable=True),
    sa.Column('insurance_name', sa.String(length=180), nullable=True),
    sa.Column('insurance_plan', sa.String(length=80), nullable=True),
    sa.Column('insurance_regime', sa.String(length=50), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('signature_hash', sa.String(length=256), nullable=True),
    sa.Column('doctor_registration', sa.String(length=50), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('safety_report_json', sa.Text(), nullable=True),
    sa.Column('safety_kb_version', sa.String(length=30), nullable=True),
    sa.Column('safety_override_reason', security.EncryptedText(), nullable=True),
    sa.Column('safety_override_at', sa.DateTime(), nullable=True),
    sa.Column('verification_hash', sa.String(length=512), nullable=False),
    sa.Column('hash_seguridad', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_order_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_order_hash_seguridad'), ['hash_seguridad'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_order_order_number'), ['order_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_order_verification_hash'), ['verification_hash'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_history_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('issued_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('used_ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['issued_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_token_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_token_user_id'), ['user_id'], unique=False)

    op.create_table('patient_allergy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('substance', security.EncryptedText(), nullable=False),
    sa.Column('substance_normalized', sa.String(length=180), nullable=True),
    sa.Column('reaction', security.EncryptedText(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('notes', security.EncryptedText(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_allergy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_allergy_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_allergy_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_allergy_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_allergy_substance_normalized'), ['substance_normalized'], unique=False)

    op.create_table('patient_chronic_condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('condition', security.EncryptedText(), nullable=False),
    sa.Column('cie10_code', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('diagnosed_on', sa.Date(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_chronic_condition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_chronic_condition_cie10_code'), ['cie10_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_chronic_condition_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_chronic_condition_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_chronic_condition_status'), ['status'], unique=False)

    op.create_table('policy_network_provider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('consent_code', sa.String(length=64), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_network_provider', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_network_provider_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_network_provider_consent_code'), ['consent_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_network_provider_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_network_provider_policy_id'), ['policy_id'], unique=False)

    op.create_table('question_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('flow_data', sa.Text(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_flow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_flow_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('stock_transfer_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('target_pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('med_name', sa.String(length=180), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['source_pharmacy_id'], ['pharmacy.id'], ),
    sa.ForeignKeyConstraint(['target_pharmacy_id'], ['pharmacy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_transfer_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_transfer_request_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_transfer_request_med_name'), ['med_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_transfer_request_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_transfer_request_source_pharmacy_id'), ['source_pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_transfer_request_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_transfer_request_target_pharmacy_id'), ['target_pharmacy_id'], unique=False)

    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('closed_by', sa.String(length=50), nullable=True),
    sa.Column('reason', security.EncryptedText(), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('active_flow_id', sa.Integer(), nullable=True),
    sa.Column('active_flow_node', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('incoming_shipment_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('med_name', sa.String(length=180), nullable=False),
    sa.Column('quantity_incoming', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('reserved_ticket_ids_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['incoming_shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incoming_shipment_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incoming_shipment_item_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incoming_shipment_item_med_name'), ['med_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_incoming_shipment_item_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('medication_pickup_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('parent_ticket_id', sa.Integer(), nullable=True),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('expendedor_id', sa.Integer(), nullable=True),
    sa.Column('pickup_code', sa.String(length=24), nullable=False),
    sa.Column('pickup_hash', sa.String(length=512), nullable=False),
    sa.Column('meds_json', sa.Text(), nullable=False),
    sa.Column('delivered_json', sa.Text(), nullable=True),
    sa.Column('pickup_date', sa.String(length=10), nullable=False),
    sa.Column('pickup_time', sa.String(length=5), nullable=False),
    sa.Column('pickup_location', sa.String(length=220), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['expendedor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['medical_order.id'], ),
    sa.ForeignKeyConstraint(['parent_ticket_id'], ['medication_pickup_ticket.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacy.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_pickup_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_pickup_ticket_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_pickup_ticket_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_pickup_ticket_parent_ticket_id'), ['parent_ticket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_pickup_ticket_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_pickup_ticket_pickup_code'), ['pickup_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_medication_pickup_ticket_pickup_hash'), ['pickup_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_medication_pickup_ticket_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_pickup_ticket_status'), ['status'], unique=False)

    op.create_table('policy_invite_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('consent_code', sa.String(length=64), nullable=False),
    sa.Column('max_codes', sa.Integer(), nullable=False),
    sa.Column('generated_count', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['policy_network_provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_invite_batch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_invite_batch_consent_code'), ['consent_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_invite_batch_policy_id'), ['policy_id'], unique=False)

    op.create_table('dispensing_ledger_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('dispensed_by_id', sa.Integer(), nullable=False),
    sa.Column('med_name', sa.String(length=180), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('batch_number', sa.String(length=80), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('receiver_kind', sa.String(length=20), nullable=False),
    sa.Column('receiver_name', security.EncryptedText(), nullable=True),
    sa.Column('receiver_document_hash', sa.String(length=64), nullable=True),
    sa.Column('identity_verified', sa.Boolean(), nullable=False),
    sa.Column('dispensed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', security.EncryptedText(), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['dispensed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['medical_order.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacy.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['medication_pickup_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispensing_ledger_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispensing_ledger_entry_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispensing_ledger_entry_dispensed_at'), ['dispensed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispensing_ledger_entry_dispensed_by_id'), ['dispensed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispensing_ledger_entry_entry_hash'), ['entry_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispensing_ledger_entry_med_name'), ['med_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispensing_ledger_entry_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispensing_ledger_entry_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispensing_ledger_entry_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispensing_ledger_entry_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('medical_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('record_type', sa.String(length=80), nullable=False),
    sa.Column('summary', security.EncryptedText(), nullable=True),
    sa.Column('diagnosis', security.EncryptedText(), nullable=True),
    sa.Column('cie10_code', sa.String(length=10), nullable=True),
    sa.Column('cups_code', sa.String(length=20), nullable=True),
    sa.Column('treatment', security.EncryptedText(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_history_cie10_code'), ['cie10_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_history_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_history_cups_code'), ['cups_code'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', security.EncryptedText(), nullable=True),
    sa.Column('file_path', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_flow_question', sa.Boolean(), nullable=True),
    sa.Column('flow_options', sa.Text(), nullable=True),
    sa.Column('flow_input_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('policy_invite_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('redeemed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['policy_invite_batch.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.ForeignKeyConstraint(['redeemed_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_invite_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_invite_code_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_invite_code_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_policy_invite_code_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_invite_code_status'), ['status'], unique=False)

    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', security.EncryptedText(), nullable=True),
    sa.Column('tags', sa.String(length=300), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_clinic_id'), ['clinic_id'], unique=False)

    op.create_table('replenishment_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('med_name', sa.String(length=180), nullable=False),
    sa.Column('required_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['medical_order.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacy.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['medication_pickup_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('replenishment_alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replenishment_alert_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_replenishment_alert_med_name'), ['med_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_replenishment_alert_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_replenishment_alert_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_replenishment_alert_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_replenishment_alert_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('stock_ledger_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('med_name', sa.String(length=180), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('committed_before', sa.Integer(), nullable=False),
    sa.Column('committed_after', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=80), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['medical_order.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacy.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['incoming_shipment.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['medication_pickup_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_ledger_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_ledger_entry_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entry_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entry_entry_hash'), ['entry_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entry_med_name'), ['med_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entry_movement_type'), ['movement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entry_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entry_performed_by_id'), ['performed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entry_pharmacy_id'), ['pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entry_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_entry_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('user_policy_enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('invite_code_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('policy_document_path', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invite_code_id'], ['policy_invite_code.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_policy_enrollment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_policy_enrollment_policy_id'), ['policy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_policy_enrollment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_policy_enrollment_user_id'), ['user_id'], unique=False)

    op.create_table('user_clinic_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.Column('policy_enrollment_id', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ),
    sa.ForeignKeyConstraint(['code_id'], ['clinic_access_code.id'], ),
    sa.ForeignKeyConstraint(['policy_enrollment_id'], ['user_policy_enrollment.id'], ),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_clinic_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_clinic_access_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_clinic_access_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_clinic_access_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_clinic_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_clinic_access_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_clinic_access_status'))
        batch_op.drop_index(batch_op.f('ix_user_clinic_access_clinic_id'))

    op.drop_table('user_clinic_access')
    with op.batch_alter_table('user_policy_enrollment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_policy_enrollment_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_policy_enrollment_status'))
        batch_op.drop_index(batch_op.f('ix_user_policy_enrollment_policy_id'))

    op.drop_table('user_policy_enrollment')
    with op.batch_alter_table('stock_ledger_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entry_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entry_stock_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entry_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entry_performed_by_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entry_order_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entry_movement_type'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entry_med_name'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entry_entry_hash'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entry_created_at'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_entry_clinic_id'))

    op.drop_table('stock_ledger_entry')
    with op.batch_alter_table('replenishment_alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replenishment_alert_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_replenishment_alert_status'))
        batch_op.drop_index(batch_op.f('ix_replenishment_alert_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_replenishment_alert_order_id'))
        batch_op.drop_index(batch_op.f('ix_replenishment_alert_med_name'))
        batch_op.drop_index(batch_op.f('ix_replenishment_alert_clinic_id'))

    op.drop_table('replenishment_alert')
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_clinic_id'))

    op.drop_table('rating')
    with op.batch_alter_table('policy_invite_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_invite_code_status'))
        batch_op.drop_index(batch_op.f('ix_policy_invite_code_policy_id'))
        batch_op.drop_index(batch_op.f('ix_policy_invite_code_code'))
        batch_op.drop_index(batch_op.f('ix_policy_invite_code_batch_id'))

    op.drop_table('policy_invite_code')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_clinic_id'))

    op.drop_table('message')
    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_history_cups_code'))
        batch_op.drop_index(batch_op.f('ix_medical_history_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_medical_history_cie10_code'))

    op.drop_table('medical_history')
    with op.batch_alter_table('dispensing_ledger_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispensing_ledger_entry_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_dispensing_ledger_entry_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_dispensing_ledger_entry_patient_id'))
        batch_op.drop_index(batch_op.f('ix_dispensing_ledger_entry_order_id'))
        batch_op.drop_index(batch_op.f('ix_dispensing_ledger_entry_med_name'))
        batch_op.drop_index(batch_op.f('ix_dispensing_ledger_entry_entry_hash'))
        batch_op.drop_index(batch_op.f('ix_dispensing_ledger_entry_dispensed_by_id'))
        batch_op.drop_index(batch_op.f('ix_dispensing_ledger_entry_dispensed_at'))
        batch_op.drop_index(batch_op.f('ix_dispensing_ledger_entry_clinic_id'))

    op.drop_table('dispensing_ledger_entry')
    with op.batch_alter_table('policy_invite_batch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_invite_batch_policy_id'))
        batch_op.drop_index(batch_op.f('ix_policy_invite_batch_consent_code'))

    op.drop_table('policy_invite_batch')
    with op.batch_alter_table('medication_pickup_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_pickup_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_medication_pickup_ticket_priority'))
        batch_op.drop_index(batch_op.f('ix_medication_pickup_ticket_pickup_hash'))
        batch_op.drop_index(batch_op.f('ix_medication_pickup_ticket_pickup_code'))
        batch_op.drop_index(batch_op.f('ix_medication_pickup_ticket_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_medication_pickup_ticket_parent_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_medication_pickup_ticket_order_id'))
        batch_op.drop_index(batch_op.f('ix_medication_pickup_ticket_clinic_id'))

    op.drop_table('medication_pickup_ticket')
    with op.batch_alter_table('incoming_shipment_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incoming_shipment_item_shipment_id'))
        batch_op.drop_index(batch_op.f('ix_incoming_shipment_item_med_name'))
        batch_op.drop_index(batch_op.f('ix_incoming_shipment_item_clinic_id'))

    op.drop_table('incoming_shipment_item')
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_clinic_id'))

    op.drop_table('chat')
    with op.batch_alter_table('stock_transfer_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_transfer_request_target_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_stock_transfer_request_status'))
        batch_op.drop_index(batch_op.f('ix_stock_transfer_request_source_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_stock_transfer_request_requester_id'))
        batch_op.drop_index(batch_op.f('ix_stock_transfer_request_med_name'))
        batch_op.drop_index(batch_op.f('ix_stock_transfer_request_clinic_id'))

    op.drop_table('stock_transfer_request')
    with op.batch_alter_table('question_flow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_flow_clinic_id'))

    op.drop_table('question_flow')
    with op.batch_alter_table('policy_network_provider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_network_provider_policy_id'))
        batch_op.drop_index(batch_op.f('ix_policy_network_provider_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_policy_network_provider_consent_code'))
        batch_op.drop_index(batch_op.f('ix_policy_network_provider_clinic_id'))

    op.drop_table('policy_network_provider')
    with op.batch_alter_table('patient_chronic_condition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_chronic_condition_status'))
        batch_op.drop_index(batch_op.f('ix_patient_chronic_condition_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_chronic_condition_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_patient_chronic_condition_cie10_code'))

    op.drop_table('patient_chronic_condition')
    with op.batch_alter_table('patient_allergy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_allergy_substance_normalized'))
        batch_op.drop_index(batch_op.f('ix_patient_allergy_status'))
        batch_op.drop_index(batch_op.f('ix_patient_allergy_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_allergy_clinic_id'))

    op.drop_table('patient_allergy')
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_token_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_token_expires_at'))

    op.drop_table('password_reset_token')
    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_history_user_id'))

    op.drop_table('password_history')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))

    op.drop_table('notification')
    with op.batch_alter_table('medical_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_order_verification_hash'))
        batch_op.drop_index(batch_op.f('ix_medical_order_status'))
        batch_op.drop_index(batch_op.f('ix_medical_order_order_number'))
        batch_op.drop_index(batch_op.f('ix_medical_order_hash_seguridad'))
        batch_op.drop_index(batch_op.f('ix_medical_order_clinic_id'))

    op.drop_table('medical_order')
    with op.batch_alter_table('informed_consent_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_informed_consent_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_informed_consent_log_patient_id'))
        batch_op.drop_index(batch_op.f('ix_informed_consent_log_consent_type'))

    op.drop_table('informed_consent_log')
    with op.batch_alter_table('incoming_shipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incoming_shipment_status'))
        batch_op.drop_index(batch_op.f('ix_incoming_shipment_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_incoming_shipment_clinic_id'))

    op.drop_table('incoming_shipment')
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_clinic_id'))

    op.drop_table('favorite')
    with op.batch_alter_table('doctor_tariff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_tariff_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_tariff_clinic_id'))

    op.drop_table('doctor_tariff')
    with op.batch_alter_table('doctor_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_schedule_clinic_id'))

    op.drop_table('doctor_schedule')
    with op.batch_alter_table('data_subject_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_subject_request_user_id'))
        batch_op.drop_index(batch_op.f('ix_data_subject_request_status'))
        batch_op.drop_index(batch_op.f('ix_data_subject_request_requested_at'))
        batch_op.drop_index(batch_op.f('ix_data_subject_request_request_type'))
        batch_op.drop_index(batch_op.f('ix_data_subject_request_due_at'))
        batch_op.drop_index(batch_op.f('ix_data_subject_request_clinic_id'))

    op.drop_table('data_subject_request')
    with op.batch_alter_table('clinic_access_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_access_code_code'))
        batch_op.drop_index(batch_op.f('ix_clinic_access_code_clinic_id'))

    op.drop_table('clinic_access_code')
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_clinic_id'))

    op.drop_table('appointment')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_policy_consent_code'))
        batch_op.drop_index(batch_op.f('ix_user_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_user_cedula_hash'))

    op.drop_table('user')
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_stock_nombre_med'))
        batch_op.drop_index(batch_op.f('ix_stock_medicamento'))
        batch_op.drop_index(batch_op.f('ix_stock_clinic_id'))

    op.drop_table('stock')
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pharmacy_clinic_id'))

    op.drop_table('pharmacy')
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_item_clinic_id'))

    op.drop_table('inventory_item')
    with op.batch_alter_table('retention_policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retention_policy_record_type'))

    op.drop_table('retention_policy')
    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_code'))

    op.drop_table('policy')
    with op.batch_alter_table('payment_verification_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_verification_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_payment_verification_ticket_patient_id'))
        batch_op.drop_index(batch_op.f('ix_payment_verification_ticket_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_payment_verification_ticket_clinic_id'))

    op.drop_table('payment_verification_ticket')
    with op.batch_alter_table('patient_doctor_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_doctor_subscription_status'))
        batch_op.drop_index(batch_op.f('ix_patient_doctor_subscription_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_doctor_subscription_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_patient_doctor_subscription_clinic_id'))

    op.drop_table('patient_doctor_subscription')
    with op.batch_alter_table('login_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempt_locked_until'))
        batch_op.drop_index(batch_op.f('ix_login_attempt_attempt_key'))

    op.drop_table('login_attempt')
    op.drop_table('lead')
    with op.batch_alter_table('jwt_revoked_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jwt_revoked_token_jti'))

    op.drop_table('jwt_revoked_token')
    with op.batch_alter_table('cups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cups_code'))

    op.drop_table('cups')
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinic_policy_consent_code'))
        batch_op.drop_index(batch_op.f('ix_clinic_habilitacion_code'))

    op.drop_table('clinic')
    with op.batch_alter_table('cie10', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cie10_code'))

    op.drop_table('cie10')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_event'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entry_hash'))
        batch_op.drop_index(batch_op.f('ix_audit_log_clinic_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
