"""Facturacion, receta conforme Res 1403 de 2007, configuracion legal

Revision ID: 8d7b0240d41f
Revises: e179c8c239ec
Create Date: 2026-09-06 20:36:12.076876

"""
from alembic import op
import sqlalchemy as sa

# `EncryptedText` es un tipo propio: las migraciones que tocan columnas
# cifradas lo referencian como `security.EncryptedText()`.
import security


# revision identifiers, used by Alembic.
revision = '8d7b0240d41f'
down_revision = 'e179c8c239ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issuer_kind', sa.String(length=30), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('legal_name', sa.String(length=220), nullable=False),
    sa.Column('document_type', sa.String(length=4), nullable=False),
    sa.Column('document_number', sa.String(length=40), nullable=False),
    sa.Column('verification_digit', sa.String(length=1), nullable=True),
    sa.Column('fiscal_address', sa.String(length=300), nullable=True),
    sa.Column('department_code', sa.String(length=2), nullable=True),
    sa.Column('municipality_code', sa.String(length=3), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('is_vat_responsible', sa.Boolean(), nullable=False),
    sa.Column('tax_regime', sa.String(length=60), nullable=True),
    sa.Column('economic_activity_code', sa.String(length=10), nullable=True),
    sa.Column('resolution_number', sa.String(length=40), nullable=True),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('resolution_valid_until', sa.Date(), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=10), nullable=True),
    sa.Column('range_from', sa.Integer(), nullable=True),
    sa.Column('range_to', sa.Integer(), nullable=True),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=80), nullable=True),
    sa.Column('provider_configured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], name=op.f('fk_billing_profile_clinic_id_clinic')),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], name=op.f('fk_billing_profile_doctor_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_profile'))
    )
    with op.batch_alter_table('billing_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_profile_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_profile_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_profile_issuer_kind'), ['issuer_kind'], unique=False)

    op.create_table('legal_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name=op.f('fk_legal_configuration_updated_by_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legal_configuration'))
    )
    with op.batch_alter_table('legal_configuration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_legal_configuration_key'), ['key'], unique=True)

    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_profile_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=True),
    sa.Column('consecutive', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('buyer_name', security.EncryptedText(), nullable=True),
    sa.Column('buyer_document_type', sa.String(length=4), nullable=True),
    sa.Column('buyer_document', security.EncryptedText(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_exclusion_note', sa.String(length=300), nullable=True),
    sa.Column('concept', sa.String(length=300), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('payment_ticket_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('cufe', sa.String(length=120), nullable=True),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('provider_response', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('annulled_at', sa.DateTime(), nullable=True),
    sa.Column('annulment_reason', sa.String(length=300), nullable=True),
    sa.Column('credit_note_for_id', sa.Integer(), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name=op.f('fk_invoice_appointment_id_appointment')),
    sa.ForeignKeyConstraint(['billing_profile_id'], ['billing_profile.id'], name=op.f('fk_invoice_billing_profile_id_billing_profile')),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], name=op.f('fk_invoice_chat_id_chat')),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], name=op.f('fk_invoice_clinic_id_clinic')),
    sa.ForeignKeyConstraint(['credit_note_for_id'], ['invoice.id'], name=op.f('fk_invoice_credit_note_for_id_invoice')),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], name=op.f('fk_invoice_patient_id_user')),
    sa.ForeignKeyConstraint(['payment_ticket_id'], ['payment_verification_ticket.id'], name=op.f('fk_invoice_payment_ticket_id_payment_verification_ticket')),
    sa.ForeignKeyConstraint(['subscription_id'], ['patient_doctor_subscription.id'], name=op.f('fk_invoice_subscription_id_patient_doctor_subscription')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice'))
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_billing_profile_id'), ['billing_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_cufe'), ['cufe'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_entry_hash'), ['entry_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_issued_at'), ['issued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoice_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_status'), ['status'], unique=False)

    op.create_table('invoice_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('cups_code', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_invoice_line_invoice_id_invoice')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_line'))
    )
    with op.batch_alter_table('invoice_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_line_invoice_id'), ['invoice_id'], unique=False)

    with op.batch_alter_table('medical_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_document_type', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('patient_document', security.EncryptedText(), nullable=True))
        batch_op.add_column(sa.Column('patient_address', security.EncryptedText(), nullable=True))
        batch_op.add_column(sa.Column('patient_phone', security.EncryptedText(), nullable=True))
        batch_op.add_column(sa.Column('clinical_record_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('care_modality', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('telemedicine_consent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('annulled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('annulled_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('annulment_reason', security.EncryptedText(), nullable=True))
        batch_op.add_column(sa.Column('replaced_by_order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mipres_number', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_medical_order_clinical_record_number'), ['clinical_record_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_order_mipres_number'), ['mipres_number'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_medical_order_telemedicine_consent_id_informed_consent_log'), 'informed_consent_log', ['telemedicine_consent_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_medical_order_annulled_by_id_user'), 'user', ['annulled_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_medical_order_replaced_by_order_id_medical_order'), 'medical_order', ['replaced_by_order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_medical_order_replaced_by_order_id_medical_order'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_medical_order_annulled_by_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_medical_order_telemedicine_consent_id_informed_consent_log'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_medical_order_mipres_number'))
        batch_op.drop_index(batch_op.f('ix_medical_order_clinical_record_number'))
        batch_op.drop_column('mipres_number')
        batch_op.drop_column('replaced_by_order_id')
        batch_op.drop_column('annulment_reason')
        batch_op.drop_column('annulled_by_id')
        batch_op.drop_column('annulled_at')
        batch_op.drop_column('telemedicine_consent_id')
        batch_op.drop_column('care_modality')
        batch_op.drop_column('clinical_record_number')
        batch_op.drop_column('patient_phone')
        batch_op.drop_column('patient_address')
        batch_op.drop_column('patient_document')
        batch_op.drop_column('patient_document_type')

    with op.batch_alter_table('invoice_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_line_invoice_id'))

    op.drop_table('invoice_line')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_status'))
        batch_op.drop_index(batch_op.f('ix_invoice_patient_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoice_issued_at'))
        batch_op.drop_index(batch_op.f('ix_invoice_entry_hash'))
        batch_op.drop_index(batch_op.f('ix_invoice_cufe'))
        batch_op.drop_index(batch_op.f('ix_invoice_clinic_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_billing_profile_id'))

    op.drop_table('invoice')
    with op.batch_alter_table('legal_configuration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_legal_configuration_key'))

    op.drop_table('legal_configuration')
    with op.batch_alter_table('billing_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_profile_issuer_kind'))
        batch_op.drop_index(batch_op.f('ix_billing_profile_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_billing_profile_clinic_id'))

    op.drop_table('billing_profile')
    # ### end Alembic commands ###
