"""Indice unico parcial del horario de cita

Revision ID: e179c8c239ec
Revises: 2f0500654aaf
Create Date: 2026-09-06 19:52:05.243188

"""
from alembic import op
import sqlalchemy as sa

# `EncryptedText` es un tipo propio: las migraciones que tocan columnas
# cifradas lo referencian como `security.EncryptedText()`.
import security


# revision identifiers, used by Alembic.
revision = 'e179c8c239ec'
down_revision = '2f0500654aaf'
branch_labels = None
depends_on = None


def upgrade():
    # --- Saneamiento previo -------------------------------------------------
    #
    # Antes de esta version, la reserva de cita era "consultar y luego insertar"
    # sin nada que impidiera que dos pacientes tomaran el mismo horario a la vez.
    # Una base en produccion puede tener ya esos duplicados, y el indice unico no
    # se puede crear sobre ellos.
    #
    # Los duplicados no se borran: son historia clinica. Se conserva la cita mas
    # antigua de cada horario —la que se reservo primero— y las posteriores pasan
    # a 'cancelada', que es un estado que el indice parcial excluye. Asi el
    # registro sobrevive y el conflicto queda visible para quien tenga que
    # reprogramar al paciente.
    conexion = op.get_bind()

    duplicados = conexion.execute(sa.text("""
        SELECT id FROM appointment
        WHERE status NOT IN ('cancelada', 'no_show')
          AND id NOT IN (
              SELECT MIN(id) FROM appointment
              WHERE status NOT IN ('cancelada', 'no_show')
              GROUP BY doctor_id, date, time
          )
    """)).fetchall()

    if duplicados:
        ids = [fila[0] for fila in duplicados]
        print(
            f'  AVISO: {len(ids)} cita(s) compartian horario con otra. '
            'Se marcan como canceladas y se conservan; revisa y reprograma '
            f'a esos pacientes. IDs: {ids[:50]}'
        )
        conexion.execute(
            sa.text("""
                UPDATE appointment
                SET status = 'cancelada',
                    description = COALESCE(description, '')
                WHERE id IN :ids
            """).bindparams(sa.bindparam('ids', expanding=True)),
            {'ids': ids},
        )

    # --- Indice unico parcial ------------------------------------------------
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index(
            'uq_appointment_active_slot',
            ['doctor_id', 'date', 'time'],
            unique=True,
            sqlite_where=sa.text("status NOT IN ('cancelada', 'no_show')"),
            postgresql_where=sa.text("status NOT IN ('cancelada', 'no_show')"),
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index('uq_appointment_active_slot', sqlite_where=sa.text("status NOT IN ('cancelada', 'no_show')"), postgresql_where=sa.text("status NOT IN ('cancelada', 'no_show')"))

    # ### end Alembic commands ###
